'use strict';
const NODE_W=150,NODE_H=152,GAP_X=30,GAP_Y=88,PAD=16;
function computeLayout(data) {
    const ids = new Set(data.people.map(p => p.id));
    const edges = data.edges.filter(e => ids.has(e.p) && ids.has(e.c) && e.p !== e.c);
    const pairs = data.partners.filter(([a,b]) => ids.has(a) && ids.has(b) && a !== b);
    // Partner groups stay together on a generation row.
    const leader = new Map([...ids].map(id => [id,id]));
    function root(id){while(leader.get(id)!==id)id=leader.get(id);return id;}
    // Join partner rows only when doing so keeps ancestry acyclic.
    function graph(){const nodes=new Set([...ids].map(root)),adj=new Map([...nodes].map(r=>[r,new Set()])),indeg=new Map([...nodes].map(r=>[r,0]));for(const e of edges){const a=root(e.p),b=root(e.c);if(a===b)return null;if(!adj.get(a).has(b)){adj.get(a).add(b);indeg.set(b,indeg.get(b)+1);}}const queue=[...nodes].filter(r=>!indeg.get(r));for(let i=0;i<queue.length;i++)for(const b of adj.get(queue[i])){indeg.set(b,indeg.get(b)-1);if(!indeg.get(b))queue.push(b);}return queue.length===nodes.size?{queue,adj}:null;}
    for(const [a,b] of pairs){const ra=root(a),rb=root(b);if(ra===rb)continue;leader.set(rb,ra);if(!graph())leader.set(rb,rb);}
    const units=[],personUnit=new Map(),unitByRoot=new Map();
    for(const p of data.people){const r=root(p.id);if(!unitByRoot.has(r)){unitByRoot.set(r,units.length);units.push({members:[],rank:0});}const u=unitByRoot.get(r);units[u].members.push(p.id);personUnit.set(p.id,u);}
    const links=[...new Map(edges.map(e=>{const a=personUnit.get(e.p),b=personUnit.get(e.c);return [a+':'+b,{a,b}];})).values()].filter(e=>e.a!==e.b);
    const ancestry=graph();
    if(ancestry){for(const r of ancestry.queue){const a=unitByRoot.get(r);for(const next of ancestry.adj.get(r)){const b=unitByRoot.get(next);units[b].rank=Math.max(units[b].rank,units[a].rank+1);}}}
    else { // A cyclic imported relationship cannot have a valid generation order.
        for(let pass=0;pass<units.length;pass++)for(const {a,b} of links)units[b].rank=Math.min(units.length-1,Math.max(units[b].rank,units[a].rank+1));
    }
    const neighbors=units.map(()=>new Set());for(const {a,b} of links){neighbors[a].add(b);neighbors[b].add(a);}
    // One grid across the whole tree, including disconnected family groups.
    // Component-by-component widths leave unequal gaps in sparse generations.
    const pos=new Map(),rows=new Map();
    let right=PAD*2+NODE_W,bottom=PAD*2+NODE_H;
    const step=NODE_W+GAP_X;
    for(let u=0;u<units.length;u++){const r=units[u].rank;if(!rows.has(r))rows.set(r,[]);rows.get(r).push(u);}
    const ranks=[...rows.keys()].sort((a,b)=>a-b),maxSlots=Math.max(1,...[...rows.values()].map(row=>row.reduce((n,u)=>n+units[u].members.length,0))),centers=new Map();
    function locate(){for(const row of rows.values()){const count=row.reduce((n,u)=>n+units[u].members.length,0);let slot=(maxSlots-count)/2;for(const u of row){centers.set(u,slot+(units[u].members.length-1)/2);slot+=units[u].members.length;}}}
    locate();
    for(let pass=0;pass<6;pass++){const order=pass%2?[...ranks].reverse():ranks;for(const r of order){const row=rows.get(r);const score=u=>{const ns=[...neighbors[u]].filter(n=>units[n].rank!==units[u].rank);return ns.length?ns.reduce((sum,n)=>sum+centers.get(n),0)/ns.length:centers.get(u);};const scores=new Map(row.map(u=>[u,score(u)]));row.sort((a,b)=>scores.get(a)-scores.get(b));locate();}}
    for(const [r,row] of rows){const count=row.reduce((n,u)=>n+units[u].members.length,0);let slot=(maxSlots-count)/2;for(const u of row){for(const id of units[u].members){const x=PAD+slot*step,y=PAD+r*(NODE_H+GAP_Y);pos.set(id,{x,y});right=Math.max(right,x+NODE_W+PAD);bottom=Math.max(bottom,y+NODE_H+PAD);slot++;}}}
    for(const p of data.people){const at=p.position;if(at&&Number.isFinite(at.x)&&Number.isFinite(at.y)&&Math.abs(at.x)<=10000000&&Math.abs(at.y)<=10000000){pos.set(p.id,{x:at.x,y:at.y});right=Math.max(right,at.x+NODE_W+PAD);bottom=Math.max(bottom,at.y+NODE_H+PAD);}}
    const center=id=>{const p=pos.get(id);return {cx:p.x+NODE_W/2,cy:p.y+48,top:p.y,bottom:p.y+96};};
    const partnerLines=[],drawn=new Set();for(const [a,b] of pairs){const key=[a,b].sort().join(':');if(drawn.has(key))continue;drawn.add(key);const ca=center(a),cb=center(b);partnerLines.push({x1:ca.cx,y1:ca.cy,x2:cb.cx,y2:cb.cy});}
    const childPaths=[],laneByRank=new Map();for(let u=0;u<units.length;u++){const children=[...new Set(edges.filter(e=>personUnit.get(e.p)===u&&personUnit.get(e.c)!==u).map(e=>e.c))];if(!children.length)continue;const rank=units[u].rank,lane=laneByRank.get(rank)||0;laneByRank.set(rank,lane+1);const parentIds=[...new Set(edges.filter(e=>personUnit.get(e.p)===u).map(e=>e.p))];const members=parentIds.map(center),fromX=members.reduce((s,p)=>s+p.cx,0)/members.length,fromY=Math.max(...members.map(p=>p.bottom))-(members.length>1?48:0),midY=Math.max(...members.map(p=>p.bottom))+42+((lane%8)*10);for(const c of children){const cc=center(c);childPaths.push(`M ${fromX} ${fromY} V ${midY} H ${cc.cx} V ${cc.top}`);}}
    return {pos,partnerLines,childPaths,width:right,height:bottom};
}

const config=window.FAMILYTREE_CONFIG||{};
const $=id=>document.getElementById(id);
let doc={people:[],partners:[],edges:[],rev:0},selectedId=null,treeId=new URLSearchParams(location.search).get('tree'),accessToken=new URLSearchParams(location.hash.slice(1)).get('edit'),serverVersion=0,kind='partner',timer=null,dirty=false,uploading=false,conflict=false,saving=false;
const LOCAL_KEY='family-tree.local.v1';
let seq=0;
const newId=()=>`p${Date.now().toString(36)}-${++seq}-${Math.random().toString(36).slice(2,7)}`;
const selected=()=>doc.people.find(p=>p.id===selectedId);
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function years(p){return p.birth&&p.death?`${p.birth} - ${p.death}`:p.birth?`b. ${p.birth}`:p.death?`d. ${p.death}`:'';}
function initials(name){return name.trim().split(/\s+/).slice(0,2).map(s=>s[0]||'').join('').toUpperCase()||'?';}
async function rpc(name,params){if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(config.supabaseUrl)||!config.publishableKey?.startsWith('sb_publishable_'))throw Error('Supabase is not configured yet. Follow README.md.');if(new Blob([JSON.stringify(params)]).size>4900000)throw Error('Tree exceeds the 5 MB limit. Export a backup before removing photos.');const res=await fetch(config.supabaseUrl+'/rest/v1/rpc/familytree_'+name,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(params)});const result=await res.json();if(!res.ok){const e=Error(result.message||'Shared tree request failed');e.code=result.code;throw e;}return result;}
function valid(d){return d&&Array.isArray(d.people)&&d.people.length<5000&&d.people.every(p=>p&&typeof p.id==='string'&&typeof p.name==='string')&&Array.isArray(d.partners)&&d.partners.every(p=>Array.isArray(p)&&p.length===2&&p.every(x=>typeof x==='string'))&&Array.isArray(d.edges)&&d.edges.every(e=>e&&typeof e.p==='string'&&typeof e.c==='string');}
function sharedUrl(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('tree',treeId);u.hash='edit='+accessToken;return u.href;}
function showShare(){if(treeId){$('share').textContent='Copy share link';$('sharebox').hidden=false;$('shareurl').value=sharedUrl();}}
async function push(){if(!treeId||!dirty||saving||conflict)return;saving=true;const snapshot=JSON.parse(JSON.stringify(doc));try{const result=await rpc('save',{p_id:treeId,p_token:accessToken,p_version:serverVersion,p_payload:snapshot});serverVersion=result.version;if(doc.rev===snapshot.rev)dirty=false;status('Shared tree saved.');}catch(e){if(e.code==='40001')conflict=true;status(e.message+' Export a backup before reloading.',true);}finally{saving=false;if(dirty&&!conflict)status('Unsaved edits. Use Retry save or export a backup.',true);}}
async function pull(){if(!treeId||saving)return;if(dirty){await push();return;}try{if(!accessToken)throw Error('This link is missing its edit token. Ask for the complete link.');const result=await rpc('get',{p_id:treeId,p_token:accessToken});if(!valid(result.payload))throw Error('Invalid family tree');doc=result.payload;serverVersion=result.version;conflict=false;const firstLoad=!layoutPositions.size;render();if(firstLoad)fitTree();showShare();status('Shared tree loaded. Everyone with the complete link can edit.');}catch(e){status(e.message,true);}}
function update(next){doc={...next,rev:doc.rev+1};dirty=true;render();if(!treeId){try{localStorage.setItem(LOCAL_KEY,JSON.stringify(doc));dirty=false;}catch{status('This browser could not save the tree. Export a backup.',true);}}if(treeId){clearTimeout(timer);timer=setTimeout(push,700);status('Saving shared changes…');}else status(dirty?'Local save failed. Export a backup before leaving.':'Saved on this browser only. Export a backup or create a share link.');}
function avatar(p){const el=document.createElement('span');el.className='avatar';el.textContent=initials(p.name);if(p.photoData&&/^data:image\/(jpeg|png|webp);base64,/.test(p.photoData))putImage(el,p.photoData,p.name);return el;}
function putImage(el,src,name){const img=document.createElement('img');img.src=src;img.alt=`Portrait of ${name}`;img.onload=()=>{el.textContent='';el.append(img);};}
let treeOffset={x:0,y:0},field={minX:-400,minY:-400,maxX:600,maxY:600};
const FIELD_MARGIN=400;
let treeZoom=1,layoutSize={width:182,height:184},layoutPositions=new Map();
function growAroundContent(){for(const at of layoutPositions.values()){field.minX=Math.min(field.minX,at.x-FIELD_MARGIN);field.minY=Math.min(field.minY,at.y-FIELD_MARGIN);field.maxX=Math.max(field.maxX,at.x+NODE_W+FIELD_MARGIN);field.maxY=Math.max(field.maxY,at.y+NODE_H+FIELD_MARGIN);}}
function applyTreeZoom(){const canvas=$('canvas'),stage=$('treestage'),view=$('scroll');const w=Math.ceil((field.maxX-field.minX)*treeZoom),h=Math.ceil((field.maxY-field.minY)*treeZoom);treeOffset={x:Math.max(0,(view.clientWidth-w)/2)-field.minX*treeZoom,y:Math.max(0,(view.clientHeight-h)/2)-field.minY*treeZoom};canvas.style.transform=`scale(${treeZoom})`;canvas.style.left=treeOffset.x+'px';canvas.style.top=treeOffset.y+'px';canvas.style.width='0px';canvas.style.height='0px';stage.style.backgroundSize=(90*treeZoom)+'px '+(120*treeZoom)+'px';stage.style.backgroundPosition=(treeOffset.x+91*treeZoom)+'px '+(treeOffset.y+64*treeZoom)+'px';canvas.style.backgroundPosition=(46-field.minX)+'px '+(4-field.minY)+'px';stage.style.width=Math.max(w,view.clientWidth)+'px';stage.style.height=Math.max(h,view.clientHeight)+'px';$('treezoom').value=treeZoom;$('treezoomvalue').textContent=Math.round(treeZoom*100)+'%';}
function panTo(left,top){const view=$('scroll'),ox=treeOffset.x,oy=treeOffset.y,margin=80,extra=Math.max(400,view.clientWidth/treeZoom);if(left<margin)field.minX-=extra;if(top<margin)field.minY-=extra;if(left+view.clientWidth>view.scrollWidth-margin)field.maxX+=extra;if(top+view.clientHeight>view.scrollHeight-margin)field.maxY+=extra;applyTreeZoom();const dx=treeOffset.x-ox,dy=treeOffset.y-oy;view.scrollLeft=left+dx;view.scrollTop=top+dy;if(gesture?.type==='pan'){gesture.left+=dx;gesture.top+=dy;}}
function viewAnchor(){const view=$('scroll');if(!layoutPositions.size)return null;const x=(view.scrollLeft+view.clientWidth/2-treeOffset.x)/treeZoom,y=(view.scrollTop+view.clientHeight/2-treeOffset.y)/treeZoom;let best=null,d=Infinity;for(const [id,p] of layoutPositions){const dist=(p.x+NODE_W/2-x)**2+(p.y+48-y)**2;if(dist<d){d=dist;best={id,dx:treeOffset.x+(p.x+NODE_W/2)*treeZoom-view.scrollLeft,dy:treeOffset.y+(p.y+48)*treeZoom-view.scrollTop};}}return best;}
function restoreView(anchor){const p=anchor&&layoutPositions.get(anchor.id);if(!p)return;const view=$('scroll');view.scrollLeft=treeOffset.x+(p.x+NODE_W/2)*treeZoom-anchor.dx;view.scrollTop=treeOffset.y+(p.y+48)*treeZoom-anchor.dy;}
function focusTreePerson(id){const p=layoutPositions.get(id);if(!p)return;const view=$('scroll');view.scrollLeft=treeOffset.x+(p.x+NODE_W/2)*treeZoom-view.clientWidth/2;view.scrollTop=treeOffset.y+(p.y+48)*treeZoom-view.clientHeight/2;}
function setTreeZoom(value,point){const view=$('scroll'),rect=view.getBoundingClientRect();const px=point?point.x-rect.left:view.clientWidth/2,py=point?point.y-rect.top:view.clientHeight/2;const x=(view.scrollLeft+px-treeOffset.x)/treeZoom,y=(view.scrollTop+py-treeOffset.y)/treeZoom;treeZoom=Math.max(.15,Math.min(2.5,value));applyTreeZoom();view.scrollLeft=treeOffset.x+x*treeZoom-px;view.scrollTop=treeOffset.y+y*treeZoom-py;}
function fitTree(){const view=$('scroll');if(!layoutPositions.size)return;const pts=[...layoutPositions.values()],minX=Math.min(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxX=Math.max(...pts.map(p=>p.x+NODE_W)),maxY=Math.max(...pts.map(p=>p.y+NODE_H));treeZoom=Math.max(.15,Math.min(1,(view.clientWidth-24)/(maxX-minX+32),(view.clientHeight-24)/(maxY-minY+32)));applyTreeZoom();view.scrollLeft=treeOffset.x+(minX+maxX)/2*treeZoom-view.clientWidth/2;view.scrollTop=treeOffset.y+(minY+maxY)/2*treeZoom-view.clientHeight/2;}
$('treezoom').oninput=()=>setTreeZoom(Number($('treezoom').value));$('zoomout').onclick=()=>setTreeZoom(treeZoom/1.2);$('zoomin').onclick=()=>setTreeZoom(treeZoom*1.2);$('zoomfit').onclick=fitTree;
const treePointers=new Map();let gesture=null,suppressTreeClickUntil=0,nodeDrag=null;
function startGesture(){const ps=[...treePointers.values()];const view=$('scroll');if(ps.length===2){const mid={x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2},rect=view.getBoundingClientRect();gesture={type:'pinch',distance:Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),zoom:treeZoom,x:(view.scrollLeft+mid.x-rect.left-treeOffset.x)/treeZoom,y:(view.scrollTop+mid.y-rect.top-treeOffset.y)/treeZoom};}else if(ps.length===1)gesture={type:'pan',x:ps[0].x,y:ps[0].y,left:view.scrollLeft,top:view.scrollTop};else gesture=null;}
$('scroll').addEventListener('pointerdown',e=>{if(e.button!==0)return;treePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('scroll').setPointerCapture(e.pointerId);const node=e.target.closest('.node');if(treePointers.size===1&&node){const p=doc.people.find(p=>p.id===node.dataset.personId),at=layoutPositions.get(p.id);nodeDrag={id:p.id,x:e.clientX,y:e.clientY,at:{...at},old:p.position,moved:false,left:$('scroll').scrollLeft,top:$('scroll').scrollTop,offset:{...treeOffset}};}if(treePointers.size===2){if(nodeDrag?.moved)finishNodeDrag(false);nodeDrag=null;}startGesture();});
function finishNodeDrag(commit){if(!nodeDrag)return;const drag=nodeDrag;nodeDrag=null;uploading=false;if(drag.moved){if(commit){doc={...doc,people:doc.people.map(p=>p.id===drag.id?{...p,position:{x:PAD+Math.round((p.position.x-PAD)/90)*90,y:PAD+Math.round((p.position.y-PAD)/120)*120}}:p)};update(doc);focusTreePerson(drag.id);}else{doc={...doc,people:doc.people.map(p=>{if(p.id!==drag.id)return p;const q={...p};if(drag.old)q.position=drag.old;else delete q.position;return q;})};render();}}}
$('scroll').addEventListener('pointermove',e=>{if(!treePointers.has(e.pointerId)||!gesture)return;treePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const view=$('scroll');if(nodeDrag&&treePointers.size===1){const dx=e.clientX-nodeDrag.x,dy=e.clientY-nodeDrag.y;if(Math.hypot(dx,dy)>6||nodeDrag.moved){e.preventDefault();nodeDrag.moved=true;uploading=true;suppressTreeClickUntil=Date.now()+350;const position={x:nodeDrag.at.x+(dx+view.scrollLeft-nodeDrag.left-(treeOffset.x-nodeDrag.offset.x))/treeZoom,y:nodeDrag.at.y+(dy+view.scrollTop-nodeDrag.top-(treeOffset.y-nodeDrag.offset.y))/treeZoom};doc={...doc,people:doc.people.map(p=>p.id===nodeDrag.id?{...p,position}:p)};const left=view.scrollLeft,top=view.scrollTop,ox=treeOffset.x,oy=treeOffset.y;render();view.scrollLeft=left+treeOffset.x-ox;view.scrollTop=top+treeOffset.y-oy;const rect=view.getBoundingClientRect();let sx=0,sy=0;if(e.clientX<rect.left+48)sx=-24;else if(e.clientX>rect.right-48)sx=24;if(e.clientY<rect.top+48)sy=-24;else if(e.clientY>rect.bottom-48)sy=24;if(sx||sy)panTo(view.scrollLeft+sx,view.scrollTop+sy);}return;}if(gesture.type==='pinch'&&treePointers.size===2){e.preventDefault();suppressTreeClickUntil=Date.now()+350;const ps=[...treePointers.values()],rect=view.getBoundingClientRect(),mid={x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2};treeZoom=Math.max(.15,Math.min(2.5,gesture.zoom*Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y)/Math.max(1,gesture.distance)));applyTreeZoom();view.scrollLeft=treeOffset.x+gesture.x*treeZoom-(mid.x-rect.left);view.scrollTop=treeOffset.y+gesture.y*treeZoom-(mid.y-rect.top);}else if(gesture.type==='pan'){const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)>5){e.preventDefault();suppressTreeClickUntil=Date.now()+350;panTo(gesture.left-dx,gesture.top-dy);}}});
for(const name of ['pointerup','pointercancel'])$('scroll').addEventListener(name,e=>{const drag=nodeDrag,moved=Date.now()<suppressTreeClickUntil;finishNodeDrag(name==='pointerup');treePointers.delete(e.pointerId);if(name==='pointerup'&&!moved&&drag){suppressTreeClickUntil=Date.now()+350;openPerson(drag.id);}startGesture();});
$('resetpositions').onclick=()=>{update({...doc,people:doc.people.map(p=>{const q={...p};delete q.position;return q;})});fitTree();};
$('resetpersonposition').onclick=()=>{const p=selected();if(!p)return;update({...doc,people:doc.people.map(x=>{if(x.id!==p.id)return x;const q={...x};delete q.position;return q;})});focusTreePerson(p.id);};
$('scroll').addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();setTreeZoom(treeZoom*Math.exp(-e.deltaY*.005),{x:e.clientX,y:e.clientY});}},{passive:false});
function render(){const anchor=viewAnchor();const empty=doc.people.length===0;$('empty').hidden=!empty;$('scroll').hidden=empty;const canvas=$('canvas');canvas.replaceChildren();if(!empty){const l=computeLayout(doc);layoutSize={width:l.width,height:l.height};layoutPositions=l.pos;growAroundContent();canvas.style.width=l.width+'px';canvas.style.height=l.height+'px';const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('class','links');svg.setAttribute('width',field.maxX-field.minX);svg.setAttribute('height',field.maxY-field.minY);svg.setAttribute('viewBox',`${field.minX} ${field.minY} ${field.maxX-field.minX} ${field.maxY-field.minY}`);svg.style.left=field.minX+'px';svg.style.top=field.minY+'px';svg.setAttribute('aria-hidden','true');for(const line of l.partnerLines){const el=document.createElementNS(ns,'line');for(const k of ['x1','y1','x2','y2'])el.setAttribute(k,line[k]);el.setAttribute('class','partner-line');svg.append(el);}for(const d of l.childPaths){const el=document.createElementNS(ns,'path');el.setAttribute('d',d);el.setAttribute('class','child-line');svg.append(el);}canvas.append(svg);for(const p of doc.people){const at=l.pos.get(p.id);if(!at)continue;const node=document.createElement('button');node.className='node'+(selectedId===p.id?' selected':'');node.style.left=at.x+'px';node.style.top=at.y+'px';node.dataset.personId=p.id;node.title=`Edit ${p.name}`;node.setAttribute('aria-label',`Edit ${p.name}`);node.append(avatar(p));const name=document.createElement('span');name.className='node-name';name.textContent=p.name;node.append(name);if(years(p)){const y=document.createElement('span');y.className='node-years';y.textContent=years(p);node.append(y);}node.onclick=()=>{if(Date.now()>=suppressTreeClickUntil)openPerson(p.id);};canvas.append(node);}}if(empty){layoutPositions=new Map();$('treestage').style.width=$('treestage').style.height='0px';}else{applyTreeZoom();restoreView(anchor);}if(!selected())$('panel').hidden=true;else renderFamilyDescription();}
function openPerson(id){selectedId=id;render();const p=selected();if(!p)return;$('panel').hidden=false;$('paneltitle').textContent=p.name;renderFamilyDescription();for(const k of ['name','birth','death','note'])$(k).value=p[k]||'';$('portrait').replaceChildren(avatar(p));$('removephoto').hidden=!p.photo&&!p.photoData;$('recropphoto').hidden=!p.photoData;$('confirm').hidden=true;$('relative').hidden=true;focusTreePerson(id);}

$('add').onclick=()=>{const id=newId();update({...doc,people:[...doc.people,{id,name:'New relative'}]});openPerson(id);};
$('close').onclick=()=>{selectedId=null;render();$('panel').hidden=true;};
$('edit').onsubmit=e=>{e.preventDefault();const p=selected();if(!p)return;update({...doc,people:doc.people.map(x=>x.id===p.id?{...x,name:$('name').value.trim()||p.name,birth:$('birth').value.trim(),death:$('death').value.trim(),note:$('note').value.trim()}:x)});$('paneltitle').textContent=selected().name;};
$('share').onclick=async()=>{if(treeId){try{await navigator.clipboard.writeText(sharedUrl());status('Share link copied.');}catch{$('shareurl').focus();$('shareurl').select();status('Copy the selected share link.');}return;}$('share').disabled=true;try{const id=crypto.randomUUID(),token=crypto.randomUUID(),snapshot=JSON.parse(JSON.stringify(doc));const result=await rpc('create',{p_id:id,p_token:token,p_payload:snapshot});treeId=id;accessToken=token;serverVersion=result.version;dirty=false;history.replaceState(null,'',sharedUrl());showShare();status('Share link ready. Anyone with the complete link can edit.');}catch(e){status(e.message,true);}finally{$('share').disabled=false;}};
$('retry').onclick=()=>{if(conflict){status('Another person saved changes. Export your edits, then reload.',true);return;}void push();};
// Keep the original upload in memory only while choosing its crop.
let cropState=null, cropDrag=null;
const cropDialog=$('cropdialog'), cropCanvas=$('croppreview');
function cropSide(){return Math.min(cropState.img.naturalWidth,cropState.img.naturalHeight)/Number($('cropzoom').value);}
function cropPosition(){const s=cropSide(),img=cropState.img;return {s,x:(img.naturalWidth-s)*(1-Number($('cropx').value)/100)/2,y:(img.naturalHeight-s)*(1-Number($('cropy').value)/100)/2};}
function drawCrop(){if(!cropState)return;const {s,x,y}=cropPosition(),ctx=cropCanvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,600,600);ctx.drawImage(cropState.img,x,y,s,s,0,0,600,600);ctx.save();ctx.fillStyle='rgba(0,0,0,.38)';ctx.beginPath();ctx.rect(0,0,600,600);ctx.arc(300,300,298,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='white';ctx.lineWidth=3;ctx.beginPath();ctx.arc(300,300,298,0,Math.PI*2);ctx.stroke();ctx.restore();$('cropzoomvalue').textContent=Number($('cropzoom').value).toFixed(1)+'×';}
function resetCrop(){$('cropzoom').value='1';$('cropx').value=$('cropy').value='0';drawCrop();}
function finishCrop(){if(cropState?.url)URL.revokeObjectURL(cropState.url);cropState=null;cropDrag=null;uploading=false;$('photo').disabled=false;$('photo').value='';if(cropDialog.open)cropDialog.close();}
async function openCrop(src,id,url=null){uploading=true;$('photo').disabled=true;try{const img=new Image();img.src=src;await img.decode();if(!doc.people.some(p=>p.id===id))throw Error('This person is no longer in the tree.');cropState={img,id,url};resetCrop();cropDialog.showModal();$('cropzoom').focus();}catch(e){if(url)URL.revokeObjectURL(url);finishCrop();status('Could not open photo: '+e.message,true);}}
for(const id of ['cropzoom','cropx','cropy'])$(id).oninput=drawCrop;
$('cropreset').onclick=resetCrop;
$('cropcancel').onclick=finishCrop;
cropDialog.addEventListener('cancel',e=>{e.preventDefault();finishCrop();});
cropDialog.addEventListener('close',()=>{if(cropState)finishCrop();});
cropCanvas.onpointerdown=e=>{if(!cropState)return;e.preventDefault();cropCanvas.setPointerCapture(e.pointerId);const pos=cropPosition();cropDrag={px:e.clientX,py:e.clientY,x:pos.x,y:pos.y,s:pos.s};};
cropCanvas.onpointermove=e=>{if(!cropDrag||!cropState)return;const {img}=cropState,b=cropCanvas.getBoundingClientRect();const x=cropDrag.x-(e.clientX-cropDrag.px)*cropDrag.s/b.width,y=cropDrag.y-(e.clientY-cropDrag.py)*cropDrag.s/b.height;const dx=img.naturalWidth-cropSide(),dy=img.naturalHeight-cropSide();$('cropx').value=dx?Math.max(-100,Math.min(100,100-200*x/dx)):0;$('cropy').value=dy?Math.max(-100,Math.min(100,100-200*y/dy)):0;drawCrop();};
for(const event of ['pointerup','pointercancel','lostpointercapture'])cropCanvas.addEventListener(event,()=>{cropDrag=null;});
$('cropapply').onclick=()=>{if(!cropState)return;try{const {id,img}=cropState,{s,x,y}=cropPosition(),canvas=document.createElement('canvas');canvas.width=canvas.height=240;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,240,240);ctx.drawImage(img,x,y,s,s,0,0,240,240);let image;for(const q of [.82,.65,.48,.3]){const result=canvas.toDataURL('image/jpeg',q);if(result.length<70000){image=result;break;}}if(!image)throw Error('This image could not be compressed enough. Try a simpler photo.');if(!doc.people.some(p=>p.id===id))throw Error('This person is no longer in the tree.');update({...doc,people:doc.people.map(p=>{if(p.id!==id)return p;const next={...p,photoData:image};delete next.photo;return next;})});if(selectedId===id){$('portrait').replaceChildren(avatar(selected()));$('removephoto').hidden=false;$('recropphoto').hidden=false;}finishCrop();}catch(e){status(e.message,true);}};
$('photo').onchange=()=>{const p=selected(),file=$('photo').files[0];if(!p||!file)return;if(!/^image\/(jpeg|png|webp|gif)$/.test(file.type)||file.size>15*1024*1024){status(file.size>15*1024*1024?'Choose a photo smaller than 15 MB.':'Choose a JPG, PNG, WebP or GIF photo.',true);$('photo').value='';return;}const url=URL.createObjectURL(file);void openCrop(url,p.id,url);};
$('recropphoto').onclick=()=>{const p=selected();if(p?.photoData)void openCrop(p.photoData,p.id);};
$('removephoto').onclick=()=>{const p=selected();if(!p)return;update({...doc,people:doc.people.map(x=>{if(x.id!==p.id)return x;const next={...x};delete next.photo;delete next.photoData;return next;})});$('portrait').replaceChildren(avatar(selected()));$('removephoto').hidden=true;$('recropphoto').hidden=true;};
function renderFamilyDescription(){const p=selected();if(!p)return;for(const [id,match,key] of [['parentlist','c','p'],['childlist','p','c']]){const people=[...new Set(doc.edges.filter(e=>e[match]===p.id).map(e=>e[key]))].map(id=>doc.people.find(x=>x.id===id)).filter(Boolean);const list=$(id);list.replaceChildren();if(!people.length){const li=document.createElement('li');li.textContent='None linked';list.append(li);}else for(const person of people){const li=document.createElement('li'),button=document.createElement('button');button.type='button';button.textContent=person.name;button.onclick=()=>openPerson(person.id);li.append(button);list.append(li);}}}
function syncRelativeMode(){const existing=$('relmode').value==='existing';$('existingbox').hidden=!existing;$('newnamebox').hidden=existing;$('relname').required=!existing;$('existingperson').required=existing;}
window.addEventListener('resize',()=>{const anchor=viewAnchor();applyTreeZoom();restoreView(anchor);});
$('relmode').onchange=syncRelativeMode;
document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;$('relative').hidden=false;$('reltitle').textContent=`Add a ${kind}`;$('relname').value='';$('relmode').value='new';syncRelativeMode();const p=selected();$('relmodebox').hidden=kind==='partner';const linked=new Set(doc.edges.filter(e=>kind==='parent'?e.c===p.id:e.p===p.id).map(e=>kind==='parent'?e.p:e.c));const names=doc.people.filter(x=>x.id!==p.id&&!linked.has(x.id)).sort((a,b)=>a.name.localeCompare(b.name));$('existingperson').replaceChildren(new Option('Choose a person',''),...names.map(x=>new Option(x.name+(x.birth?' (b. '+x.birth+')':''),x.id)));const partners=doc.partners.filter(([a,b])=>a===p.id||b===p.id).map(([a,b])=>a===p.id?b:a);$('coparentbox').hidden=kind!=='child'||!partners.length;$('coparent').replaceChildren(new Option('No other parent',''),...partners.map(id=>new Option(doc.people.find(x=>x.id===id)?.name||'Partner',id)));$('partnerbox').hidden=kind!=='parent'||doc.edges.filter(e=>e.c===p.id).length!==1;$('linkpartner').checked=true;$('relname').focus();});
$('cancelrelative').onclick=()=>{$('relative').hidden=true;};
function acyclic(people,edges){const ids=new Set(people.map(p=>p.id)),adj=new Map([...ids].map(id=>[id,[]])),degree=new Map([...ids].map(id=>[id,0]));for(const e of edges){if(e.p===e.c)return false;if(!ids.has(e.p)||!ids.has(e.c))continue;adj.get(e.p).push(e.c);degree.set(e.c,degree.get(e.c)+1);}const queue=[...ids].filter(id=>degree.get(id)===0);for(let i=0;i<queue.length;i++)for(const c of adj.get(queue[i])){degree.set(c,degree.get(c)-1);if(degree.get(c)===0)queue.push(c);}return queue.length===ids.size;}
$('relative').onsubmit=e=>{e.preventDefault();const p=selected();if(!p)return;const existing=kind!=='partner'&&$('relmode').value==='existing',name=$('relname').value.trim(),id=existing?$('existingperson').value:newId();if(existing&&!doc.people.some(x=>x.id===id)){status('Choose an existing person.',true);return;}if(!existing&&!name)return;const next={...doc,people:existing?[...doc.people]:[...doc.people,{id,name}],partners:[...doc.partners],edges:[...doc.edges]};function edge(a,b){if(!next.edges.some(e=>e.p===a&&e.c===b))next.edges.push({p:a,c:b});}function partner(a,b){if(a!==b&&!next.partners.some(pair=>pair.includes(a)&&pair.includes(b)))next.partners.push([a,b]);}if(kind==='partner')partner(p.id,id);if(kind==='child'){edge(p.id,id);if($('coparent').value)edge($('coparent').value,id);}if(kind==='parent'){const other=doc.edges.filter(e=>e.c===p.id);edge(id,p.id);if(other.length===1&&$('linkpartner').checked)partner(other[0].p,id);}if(!acyclic(next.people,next.edges)){status('That link would make someone their own ancestor. No changes were saved.',true);return;}update(next);openPerson(p.id);$('relative').hidden=true;};
$('remove').onclick=()=>{$('confirm').hidden=false;};$('keep').onclick=()=>{$('confirm').hidden=true;};$('confirmremove').onclick=()=>{const id=selectedId,at=layoutPositions.get(id);const remaining=doc.people.filter(p=>p.id!==id);remaining.sort((a,b)=>{const pa=layoutPositions.get(a.id),pb=layoutPositions.get(b.id);return Math.hypot(pa.x-at.x,pa.y-at.y)-Math.hypot(pb.x-at.x,pb.y-at.y);});const nextId=remaining[0]?.id;selectedId=null;update({...doc,people:doc.people.filter(p=>p.id!==id),partners:doc.partners.filter(pair=>!pair.includes(id)),edges:doc.edges.filter(e=>e.p!==id&&e.c!==id)});if(nextId)focusTreePerson(nextId);else{$('scroll').scrollLeft=$('scroll').scrollTop=0;}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='family-tree-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);status('Backup exported, including uploaded portraits.');};
$('import').onclick=()=>{if(doc.people.length||treeId){status('Open the app without a tree link to import a backup into an empty tree. Your current tree has not changed.',true);return;}$('backup').click();};
$('backup').onchange=async()=>{const f=$('backup').files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('Backup exceeds 5 MB.');const b=JSON.parse(await f.text());if(!valid(b))throw Error('Choose a valid family-tree backup.');for(const p of b.people){if(p.photoData&&!/^data:image\/(jpeg|png|webp);base64,/.test(p.photoData))throw Error('Invalid portrait in backup.');}selectedId=null;update(b);}catch(e){status(e.message,true);}finally{$('backup').value='';}};
window.addEventListener('focus',()=>{if(!uploading)pull();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!uploading)pull();});window.addEventListener('beforeunload',e=>{if(dirty||uploading){e.preventDefault();e.returnValue='';}});
if(!treeId){try{const saved=JSON.parse(localStorage.getItem(LOCAL_KEY));if(valid(saved))doc=saved;}catch{}}
render();if(doc.people.length)fitTree();if(treeId){showShare();status('Loading shared tree…');pull();}else status(doc.people.length?'Local tree loaded from this browser. Export backups regularly.':'Start a tree. It is saved on this browser; export backups regularly.');

