'use strict';
const NODE_W=150,NODE_H=152,GAP_X=30,GAP_Y=88,PAD=16;
function computeLayout(data) {
    const ids = new Set(data.people.map(p => p.id));
    const edges = data.edges.filter(e => ids.has(e.p) && ids.has(e.c) && e.p !== e.c);
    const pairs = data.partners.filter(([a,b]) => ids.has(a) && ids.has(b) && a !== b);
    // Partner groups stay together on a generation row.
    const leader = new Map([...ids].map(id => [id,id]));
    function root(id){while(leader.get(id)!==id)id=leader.get(id);return id;}
    for(const [a,b] of pairs)leader.set(root(b),root(a));
    const units=[],personUnit=new Map(),unitByRoot=new Map();
    for(const p of data.people){const r=root(p.id);if(!unitByRoot.has(r)){unitByRoot.set(r,units.length);units.push({members:[],rank:0});}const u=unitByRoot.get(r);units[u].members.push(p.id);personUnit.set(p.id,u);}
    const links=[...new Map(edges.map(e=>{const a=personUnit.get(e.p),b=personUnit.get(e.c);return [a+':'+b,{a,b}];})).values()].filter(e=>e.a!==e.b);
    // Longest ancestor depth gives every row the same vertical step.
    for(let pass=0;pass<units.length*2;pass++){let changed=false;for(const {a,b} of links){const rank=Math.min(units.length-1,units[a].rank+1);if(units[b].rank<rank){units[b].rank=rank;changed=true;}const parentRank=Math.max(0,units[b].rank-1);if(units[a].rank<parentRank){units[a].rank=parentRank;changed=true;}}if(!changed)break;}
    const neighbors=units.map(()=>new Set());for(const {a,b} of links){neighbors[a].add(b);neighbors[b].add(a);}
    // One grid across the whole tree, including disconnected family groups.
    // Component-by-component widths leave unequal gaps in sparse generations.
    const pos=new Map(),rows=new Map();
    let right=PAD*2+NODE_W,bottom=PAD*2+NODE_H;
    const step=NODE_W+GAP_X;
    for(let u=0;u<units.length;u++){const r=units[u].rank;if(!rows.has(r))rows.set(r,[]);rows.get(r).push(u);}
    const ranks=[...rows.keys()].sort((a,b)=>a-b),maxSlots=Math.max(1,...[...rows.values()].map(row=>row.reduce((n,u)=>n+units[u].members.length,0))),centers=new Map();
    function locate(){for(const row of rows.values()){const count=row.reduce((n,u)=>n+units[u].members.length,0);let slot=(maxSlots-count)/2;for(const u of row){centers.set(u,slot+(units[u].members.length-1)/2);slot+=units[u].members.length;}}}
    locate();
    for(let pass=0;pass<6;pass++){const order=pass%2?[...ranks].reverse():ranks;for(const r of order){const row=rows.get(r);const score=u=>{const ns=[...neighbors[u]].filter(n=>units[n].rank!==units[u].rank);return ns.length?ns.reduce((sum,n)=>sum+centers.get(n),0)/ns.length:centers.get(u);};const scores=new Map(row.map(u=>[u,score(u)]));row.sort((a,b)=>scores.get(a)-scores.get(b));locate();}}
    for(const [r,row] of rows){const count=row.reduce((n,u)=>n+units[u].members.length,0);let slot=(maxSlots-count)/2;for(const u of row){for(const id of units[u].members){const x=PAD+slot*step,y=PAD+r*(NODE_H+GAP_Y);pos.set(id,{x,y});right=Math.max(right,x+NODE_W+PAD);bottom=Math.max(bottom,y+NODE_H+PAD);slot++;}}}
    const center=id=>{const p=pos.get(id);return {cx:p.x+NODE_W/2,cy:p.y+48,top:p.y,bottom:p.y+96};};
    const partnerLines=[],drawn=new Set();for(const [a,b] of pairs){const key=[a,b].sort().join(':');if(drawn.has(key))continue;drawn.add(key);const ca=center(a),cb=center(b);partnerLines.push({x1:ca.cx,y1:ca.cy,x2:cb.cx,y2:cb.cy});}
    const childPaths=[],laneByRank=new Map();for(let u=0;u<units.length;u++){const children=[...new Set(edges.filter(e=>personUnit.get(e.p)===u&&personUnit.get(e.c)!==u).map(e=>e.c))];if(!children.length)continue;const rank=units[u].rank,lane=laneByRank.get(rank)||0;laneByRank.set(rank,lane+1);const members=units[u].members.map(center),fromX=members.reduce((s,p)=>s+p.cx,0)/members.length,fromY=Math.max(...members.map(p=>p.bottom))-(members.length>1?48:0),midY=Math.max(...members.map(p=>p.bottom))+42+((lane%8)*10);for(const c of children){const cc=center(c);childPaths.push(`M ${fromX} ${fromY} V ${midY} H ${cc.cx} V ${cc.top}`);}}
    return {pos,partnerLines,childPaths,width:right,height:bottom};
}

const config=window.FAMILYTREE_CONFIG||{};
const $=id=>document.getElementById(id);
let doc={people:[],partners:[],edges:[],rev:0},selectedId=null,treeId=new URLSearchParams(location.search).get('tree'),accessToken=new URLSearchParams(location.hash.slice(1)).get('edit'),serverVersion=0,kind='partner',timer=null,dirty=false,uploading=false,conflict=false,saving=false;
const LOCAL_KEY='family-tree.local.v1';
let seq=0;
const newId=()=>`p${Date.now().toString(36)}-${++seq}-${Math.random().toString(36).slice(2,7)}`;
const selected=()=>doc.people.find(p=>p.id===selectedId);
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function years(p){return p.birth&&p.death?`${p.birth} - ${p.death}`:p.birth?`b. ${p.birth}`:p.death?`d. ${p.death}`:'';}
function initials(name){return name.trim().split(/\s+/).slice(0,2).map(s=>s[0]||'').join('').toUpperCase()||'?';}
async function rpc(name,params){if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(config.supabaseUrl)||!config.publishableKey?.startsWith('sb_publishable_'))throw Error('Supabase is not configured yet. Follow README.md.');if(new Blob([JSON.stringify(params)]).size>4900000)throw Error('Tree exceeds the 5 MB limit. Export a backup before removing photos.');const res=await fetch(config.supabaseUrl+'/rest/v1/rpc/familytree_'+name,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(params)});const result=await res.json();if(!res.ok){const e=Error(result.message||'Shared tree request failed');e.code=result.code;throw e;}return result;}
function valid(d){return d&&Array.isArray(d.people)&&d.people.length<5000&&d.people.every(p=>p&&typeof p.id==='string'&&typeof p.name==='string')&&Array.isArray(d.partners)&&d.partners.every(p=>Array.isArray(p)&&p.length===2&&p.every(x=>typeof x==='string'))&&Array.isArray(d.edges)&&d.edges.every(e=>e&&typeof e.p==='string'&&typeof e.c==='string');}
function sharedUrl(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('tree',treeId);u.hash='edit='+accessToken;return u.href;}
function showShare(){if(treeId){$('share').textContent='Copy share link';$('sharebox').hidden=false;$('shareurl').value=sharedUrl();}}
async function push(){if(!treeId||!dirty||saving||conflict)return;saving=true;const snapshot=JSON.parse(JSON.stringify(doc));try{const result=await rpc('save',{p_id:treeId,p_token:accessToken,p_version:serverVersion,p_payload:snapshot});serverVersion=result.version;if(doc.rev===snapshot.rev)dirty=false;status('Shared tree saved.');}catch(e){if(e.code==='40001')conflict=true;status(e.message+' Export a backup before reloading.',true);}finally{saving=false;if(dirty&&!conflict)status('Unsaved edits. Use Retry save or export a backup.',true);}}
async function pull(){if(!treeId||saving)return;if(dirty){await push();return;}try{if(!accessToken)throw Error('This link is missing its edit token. Ask for the complete link.');const result=await rpc('get',{p_id:treeId,p_token:accessToken});if(!valid(result.payload))throw Error('Invalid family tree');doc=result.payload;serverVersion=result.version;conflict=false;const firstLoad=!layoutPositions.size;render();if(firstLoad)fitTree();showShare();status('Shared tree loaded. Everyone with the complete link can edit.');}catch(e){status(e.message,true);}}
function update(next){doc={...next,rev:doc.rev+1};dirty=true;render();if(!treeId){try{localStorage.setItem(LOCAL_KEY,JSON.stringify(doc));dirty=false;}catch{status('This browser could not save the tree. Export a backup.',true);}}if(treeId){clearTimeout(timer);timer=setTimeout(push,700);status('Saving shared changes…');}else status(dirty?'Local save failed. Export a backup before leaving.':'Saved on this browser only. Export a backup or create a share link.');}
function avatar(p){const el=document.createElement('span');el.className='avatar';el.textContent=initials(p.name);if(p.photoData&&/^data:image\/(jpeg|png|webp);base64,/.test(p.photoData))putImage(el,p.photoData,p.name);return el;}
function putImage(el,src,name){const img=document.createElement('img');img.src=src;img.alt=`Portrait of ${name}`;img.onload=()=>{el.textContent='';el.append(img);};}
let treeZoom=1,layoutSize={width:182,height:184},layoutPositions=new Map();
function applyTreeZoom(){const canvas=$('canvas'),stage=$('treestage');canvas.style.transform=`scale(${treeZoom})`;stage.style.width=Math.ceil(layoutSize.width*treeZoom)+'px';stage.style.height=Math.ceil(layoutSize.height*treeZoom)+'px';$('treezoom').value=treeZoom;$('treezoomvalue').textContent=Math.round(treeZoom*100)+'%';}
function viewAnchor(){const view=$('scroll');if(!layoutPositions.size)return null;const x=(view.scrollLeft+view.clientWidth/2)/treeZoom,y=(view.scrollTop+view.clientHeight/2)/treeZoom;let best=null,d=Infinity;for(const [id,p] of layoutPositions){const dist=(p.x+NODE_W/2-x)**2+(p.y+48-y)**2;if(dist<d){d=dist;best={id,dx:(p.x+NODE_W/2)*treeZoom-view.scrollLeft,dy:(p.y+48)*treeZoom-view.scrollTop};}}return best;}
function restoreView(anchor){const p=anchor&&layoutPositions.get(anchor.id);if(!p)return;const view=$('scroll');view.scrollLeft=(p.x+NODE_W/2)*treeZoom-anchor.dx;view.scrollTop=(p.y+48)*treeZoom-anchor.dy;}
function focusTreePerson(id){const p=layoutPositions.get(id);if(!p)return;const view=$('scroll');view.scrollLeft=(p.x+NODE_W/2)*treeZoom-view.clientWidth/2;view.scrollTop=(p.y+48)*treeZoom-view.clientHeight/2;}
function setTreeZoom(value,point){const view=$('scroll'),rect=view.getBoundingClientRect();const px=point?point.x-rect.left:view.clientWidth/2,py=point?point.y-rect.top:view.clientHeight/2;const x=(view.scrollLeft+px)/treeZoom,y=(view.scrollTop+py)/treeZoom;treeZoom=Math.max(.15,Math.min(2.5,value));applyTreeZoom();view.scrollLeft=x*treeZoom-px;view.scrollTop=y*treeZoom-py;}
function fitTree(){const view=$('scroll');if(!doc.people.length)return;treeZoom=Math.max(.15,Math.min(1,(view.clientWidth-12)/layoutSize.width,(view.clientHeight-12)/layoutSize.height));applyTreeZoom();view.scrollLeft=view.scrollTop=0;}
$('treezoom').oninput=()=>setTreeZoom(Number($('treezoom').value));$('zoomout').onclick=()=>setTreeZoom(treeZoom/1.2);$('zoomin').onclick=()=>setTreeZoom(treeZoom*1.2);$('zoomfit').onclick=fitTree;
const treePointers=new Map();let gesture=null,suppressTreeClickUntil=0;
function startGesture(){const ps=[...treePointers.values()];const view=$('scroll');if(ps.length===2){const mid={x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2},rect=view.getBoundingClientRect();gesture={type:'pinch',distance:Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y),zoom:treeZoom,x:(view.scrollLeft+mid.x-rect.left)/treeZoom,y:(view.scrollTop+mid.y-rect.top)/treeZoom};}else if(ps.length===1)gesture={type:'pan',x:ps[0].x,y:ps[0].y,left:view.scrollLeft,top:view.scrollTop};else gesture=null;}
$('scroll').addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.target.closest('.node'))return;if(e.button!==0)return;treePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('scroll').setPointerCapture(e.pointerId);startGesture();});
$('scroll').addEventListener('pointermove',e=>{if(!treePointers.has(e.pointerId)||!gesture)return;treePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const view=$('scroll');if(gesture.type==='pinch'&&treePointers.size===2){e.preventDefault();suppressTreeClickUntil=Date.now()+350;const ps=[...treePointers.values()],rect=view.getBoundingClientRect(),mid={x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2};treeZoom=Math.max(.15,Math.min(2.5,gesture.zoom*Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y)/Math.max(1,gesture.distance)));applyTreeZoom();view.scrollLeft=gesture.x*treeZoom-(mid.x-rect.left);view.scrollTop=gesture.y*treeZoom-(mid.y-rect.top);}else if(gesture.type==='pan'){const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)>5){e.preventDefault();suppressTreeClickUntil=Date.now()+350;view.scrollLeft=gesture.left-dx;view.scrollTop=gesture.top-dy;}}});
for(const name of ['pointerup','pointercancel'])$('scroll').addEventListener(name,e=>{const moved=Date.now()<suppressTreeClickUntil;treePointers.delete(e.pointerId);if(name==='pointerup'&&!moved&&e.pointerType!=='mouse'){const node=document.elementFromPoint(e.clientX,e.clientY)?.closest('.node');if(node){suppressTreeClickUntil=Date.now()+350;openPerson(node.dataset.personId);}}startGesture();});
$('scroll').addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();setTreeZoom(treeZoom*Math.exp(-e.deltaY*.005),{x:e.clientX,y:e.clientY});}},{passive:false});
function render(){const anchor=viewAnchor();const empty=doc.people.length===0;$('empty').hidden=!empty;$('scroll').hidden=empty;const canvas=$('canvas');canvas.replaceChildren();if(!empty){const l=computeLayout(doc);layoutSize={width:l.width,height:l.height};layoutPositions=l.pos;canvas.style.width=l.width+'px';canvas.style.height=l.height+'px';const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('class','links');svg.setAttribute('width',l.width);svg.setAttribute('height',l.height);svg.setAttribute('aria-hidden','true');for(const line of l.partnerLines){const el=document.createElementNS(ns,'line');for(const k of ['x1','y1','x2','y2'])el.setAttribute(k,line[k]);el.setAttribute('class','partner-line');svg.append(el);}for(const d of l.childPaths){const el=document.createElementNS(ns,'path');el.setAttribute('d',d);el.setAttribute('class','child-line');svg.append(el);}canvas.append(svg);for(const p of doc.people){const at=l.pos.get(p.id);if(!at)continue;const node=document.createElement('button');node.className='node'+(selectedId===p.id?' selected':'');node.style.left=at.x+'px';node.style.top=at.y+'px';node.dataset.personId=p.id;node.title=`Edit ${p.name}`;node.setAttribute('aria-label',`Edit ${p.name}`);node.append(avatar(p));const name=document.createElement('span');name.className='node-name';name.textContent=p.name;node.append(name);if(years(p)){const y=document.createElement('span');y.className='node-years';y.textContent=years(p);node.append(y);}node.onclick=()=>{if(Date.now()>=suppressTreeClickUntil)openPerson(p.id);};canvas.append(node);}}if(empty){layoutPositions=new Map();$('treestage').style.width=$('treestage').style.height='0px';}else{applyTreeZoom();restoreView(anchor);}if(!selected())$('panel').hidden=true;}
function openPerson(id){selectedId=id;render();const p=selected();if(!p)return;$('panel').hidden=false;$('paneltitle').textContent=p.name;for(const k of ['name','birth','death','note'])$(k).value=p[k]||'';$('portrait').replaceChildren(avatar(p));$('removephoto').hidden=!p.photo&&!p.photoData;$('recropphoto').hidden=!p.photoData;$('confirm').hidden=true;$('relative').hidden=true;focusTreePerson(id);}

$('add').onclick=()=>{const id=newId();update({...doc,people:[...doc.people,{id,name:'New relative'}]});openPerson(id);};
$('close').onclick=()=>{selectedId=null;render();$('panel').hidden=true;};
$('edit').onsubmit=e=>{e.preventDefault();const p=selected();if(!p)return;update({...doc,people:doc.people.map(x=>x.id===p.id?{...x,name:$('name').value.trim()||p.name,birth:$('birth').value.trim(),death:$('death').value.trim(),note:$('note').value.trim()}:x)});$('paneltitle').textContent=selected().name;};
$('share').onclick=async()=>{if(treeId){try{await navigator.clipboard.writeText(sharedUrl());status('Share link copied.');}catch{$('shareurl').focus();$('shareurl').select();status('Copy the selected share link.');}return;}$('share').disabled=true;try{const id=crypto.randomUUID(),token=crypto.randomUUID(),snapshot=JSON.parse(JSON.stringify(doc));const result=await rpc('create',{p_id:id,p_token:token,p_payload:snapshot});treeId=id;accessToken=token;serverVersion=result.version;dirty=false;history.replaceState(null,'',sharedUrl());showShare();status('Share link ready. Anyone with the complete link can edit.');}catch(e){status(e.message,true);}finally{$('share').disabled=false;}};
$('retry').onclick=()=>{if(conflict){status('Another person saved changes. Export your edits, then reload.',true);return;}void push();};
// Keep the original upload in memory only while choosing its crop.
let cropState=null, cropDrag=null;
const cropDialog=$('cropdialog'), cropCanvas=$('croppreview');
function cropSide(){return Math.min(cropState.img.naturalWidth,cropState.img.naturalHeight)/Number($('cropzoom').value);}
function cropPosition(){const s=cropSide(),img=cropState.img;return {s,x:(img.naturalWidth-s)*(1-Number($('cropx').value)/100)/2,y:(img.naturalHeight-s)*(1-Number($('cropy').value)/100)/2};}
function drawCrop(){if(!cropState)return;const {s,x,y}=cropPosition(),ctx=cropCanvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,600,600);ctx.drawImage(cropState.img,x,y,s,s,0,0,600,600);ctx.save();ctx.fillStyle='rgba(0,0,0,.38)';ctx.beginPath();ctx.rect(0,0,600,600);ctx.arc(300,300,298,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='white';ctx.lineWidth=3;ctx.beginPath();ctx.arc(300,300,298,0,Math.PI*2);ctx.stroke();ctx.restore();$('cropzoomvalue').textContent=Number($('cropzoom').value).toFixed(1)+'×';}
function resetCrop(){$('cropzoom').value='1';$('cropx').value=$('cropy').value='0';drawCrop();}
function finishCrop(){if(cropState?.url)URL.revokeObjectURL(cropState.url);cropState=null;cropDrag=null;uploading=false;$('photo').disabled=false;$('photo').value='';if(cropDialog.open)cropDialog.close();}
async function openCrop(src,id,url=null){uploading=true;$('photo').disabled=true;try{const img=new Image();img.src=src;await img.decode();if(!doc.people.some(p=>p.id===id))throw Error('This person is no longer in the tree.');cropState={img,id,url};resetCrop();cropDialog.showModal();$('cropzoom').focus();}catch(e){if(url)URL.revokeObjectURL(url);finishCrop();status('Could not open photo: '+e.message,true);}}
for(const id of ['cropzoom','cropx','cropy'])$(id).oninput=drawCrop;
$('cropreset').onclick=resetCrop;
$('cropcancel').onclick=finishCrop;
cropDialog.addEventListener('cancel',e=>{e.preventDefault();finishCrop();});
cropDialog.addEventListener('close',()=>{if(cropState)finishCrop();});
cropCanvas.onpointerdown=e=>{if(!cropState)return;e.preventDefault();cropCanvas.setPointerCapture(e.pointerId);const pos=cropPosition();cropDrag={px:e.clientX,py:e.clientY,x:pos.x,y:pos.y,s:pos.s};};
cropCanvas.onpointermove=e=>{if(!cropDrag||!cropState)return;const {img}=cropState,b=cropCanvas.getBoundingClientRect();const x=cropDrag.x-(e.clientX-cropDrag.px)*cropDrag.s/b.width,y=cropDrag.y-(e.clientY-cropDrag.py)*cropDrag.s/b.height;const dx=img.naturalWidth-cropSide(),dy=img.naturalHeight-cropSide();$('cropx').value=dx?Math.max(-100,Math.min(100,100-200*x/dx)):0;$('cropy').value=dy?Math.max(-100,Math.min(100,100-200*y/dy)):0;drawCrop();};
for(const event of ['pointerup','pointercancel','lostpointercapture'])cropCanvas.addEventListener(event,()=>{cropDrag=null;});
$('cropapply').onclick=()=>{if(!cropState)return;try{const {id,img}=cropState,{s,x,y}=cropPosition(),canvas=document.createElement('canvas');canvas.width=canvas.height=240;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,240,240);ctx.drawImage(img,x,y,s,s,0,0,240,240);let image;for(const q of [.82,.65,.48,.3]){const result=canvas.toDataURL('image/jpeg',q);if(result.length<70000){image=result;break;}}if(!image)throw Error('This image could not be compressed enough. Try a simpler photo.');if(!doc.people.some(p=>p.id===id))throw Error('This person is no longer in the tree.');update({...doc,people:doc.people.map(p=>{if(p.id!==id)return p;const next={...p,photoData:image};delete next.photo;return next;})});if(selectedId===id){$('portrait').replaceChildren(avatar(selected()));$('removephoto').hidden=false;$('recropphoto').hidden=false;}finishCrop();}catch(e){status(e.message,true);}};
$('photo').onchange=()=>{const p=selected(),file=$('photo').files[0];if(!p||!file)return;if(!/^image\/(jpeg|png|webp|gif)$/.test(file.type)||file.size>15*1024*1024){status(file.size>15*1024*1024?'Choose a photo smaller than 15 MB.':'Choose a JPG, PNG, WebP or GIF photo.',true);$('photo').value='';return;}const url=URL.createObjectURL(file);void openCrop(url,p.id,url);};
$('recropphoto').onclick=()=>{const p=selected();if(p?.photoData)void openCrop(p.photoData,p.id);};
$('removephoto').onclick=()=>{const p=selected();if(!p)return;update({...doc,people:doc.people.map(x=>{if(x.id!==p.id)return x;const next={...x};delete next.photo;delete next.photoData;return next;})});$('portrait').replaceChildren(avatar(selected()));$('removephoto').hidden=true;$('recropphoto').hidden=true;};
document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;$('relative').hidden=false;$('reltitle').textContent=`Add a ${kind}`;$('relname').value='';const p=selected();const partners=doc.partners.filter(([a,b])=>a===p.id||b===p.id).map(([a,b])=>a===p.id?b:a);$('coparentbox').hidden=kind!=='child'||!partners.length;$('coparent').replaceChildren(new Option('No other parent',''),...partners.map(id=>new Option(doc.people.find(x=>x.id===id)?.name||'Partner',id)));$('partnerbox').hidden=kind!=='parent'||doc.edges.filter(e=>e.c===p.id).length!==1;$('linkpartner').checked=true;$('relname').focus();});
$('cancelrelative').onclick=()=>{$('relative').hidden=true;};
$('relative').onsubmit=e=>{e.preventDefault();const p=selected();if(!p)return;const name=$('relname').value.trim();if(!name)return;const id=newId();const next={...doc,people:[...doc.people,{id,name}],partners:[...doc.partners],edges:[...doc.edges]};if(kind==='partner')next.partners.push([p.id,id]);if(kind==='child'){next.edges.push({p:p.id,c:id});if($('coparent').value)next.edges.push({p:$('coparent').value,c:id});}if(kind==='parent'){const other=doc.edges.filter(e=>e.c===p.id);next.edges.push({p:id,c:p.id});if(other.length===1&&$('linkpartner').checked)next.partners.push([other[0].p,id]);}update(next);openPerson(id);};
$('remove').onclick=()=>{$('confirm').hidden=false;};$('keep').onclick=()=>{$('confirm').hidden=true;};$('confirmremove').onclick=()=>{const id=selectedId,at=layoutPositions.get(id);const remaining=doc.people.filter(p=>p.id!==id);remaining.sort((a,b)=>{const pa=layoutPositions.get(a.id),pb=layoutPositions.get(b.id);return Math.hypot(pa.x-at.x,pa.y-at.y)-Math.hypot(pb.x-at.x,pb.y-at.y);});const nextId=remaining[0]?.id;selectedId=null;update({...doc,people:doc.people.filter(p=>p.id!==id),partners:doc.partners.filter(pair=>!pair.includes(id)),edges:doc.edges.filter(e=>e.p!==id&&e.c!==id)});if(nextId)focusTreePerson(nextId);else{$('scroll').scrollLeft=$('scroll').scrollTop=0;}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='family-tree-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);status('Backup exported, including uploaded portraits.');};
$('import').onclick=()=>{if(doc.people.length||treeId){status('Open the app without a tree link to import a backup into an empty tree. Your current tree has not changed.',true);return;}$('backup').click();};
$('backup').onchange=async()=>{const f=$('backup').files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('Backup exceeds 5 MB.');const b=JSON.parse(await f.text());if(!valid(b))throw Error('Choose a valid family-tree backup.');for(const p of b.people){if(p.photoData&&!/^data:image\/(jpeg|png|webp);base64,/.test(p.photoData))throw Error('Invalid portrait in backup.');}selectedId=null;update(b);}catch(e){status(e.message,true);}finally{$('backup').value='';}};
window.addEventListener('focus',()=>{if(!uploading)pull();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!uploading)pull();});window.addEventListener('beforeunload',e=>{if(dirty||uploading){e.preventDefault();e.returnValue='';}});
if(!treeId){try{const saved=JSON.parse(localStorage.getItem(LOCAL_KEY));if(valid(saved))doc=saved;}catch{}}
render();if(doc.people.length)fitTree();if(treeId){showShare();status('Loading shared tree…');pull();}else status(doc.people.length?'Local tree loaded from this browser. Export backups regularly.':'Start a tree. It is saved on this browser; export backups regularly.');

